version: '3.8'

services:
  binance-proxy:
    build: .
    container_name: binance-proxy
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3002/api/health', (r) => {process.exit(r.statusCode === 200 ? 0 : 1)})"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    networks:
      - binance-network

networks:
  binance-network:
    driver: bridge
